modLoader = "lowcodefml"
loaderVersion = "[1,)"
license = "BSD-3-Clause"
issueTrackerURL = "https://github.com/lukebemishprojects/LetMeMixinPlease/issues"

[[mods]]
modId = "letmemixinplease"
version = "${version}"
displayName = "LetMeMixinPlease"
displayURL = "https://github.com/lukebemishprojects/LetMeMixinPlease"
description = "Lets you mixin, pretty please."
authors = "Luke Bemish"

[[mixins]]
config = "letmemixinplease.mixin.json"
